# Use root/example as user/password credentials
version: "3.1"

services:
    apache:
        image: ubuntu/apache2:2.4-22.04_beta
        ports:
            - 8080:80

    # node:
    #     build: .
    #     ports:
    #         - 8000:3000
    #     volumes:
    #         - .:/home/node/app

    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    # certbot:
    #     image: certbot/certbot
